### ISSUE TITLE
Evolution GUI does not open

### ISSUE THREAD

**Issue by fansari** [flathub/org.gnome.Evolution#46]
When I try to open Evolution a second time (open it first, then close and and reopen it later) I often experience that the GUI does not come up. This does not always happen but so often that it is really annoying.

I have tried to kill all processes with reference to Evolution and also logout/login from Gnome. Both methods do not fix it - only after a reboot of my PC Evolution comes up again.

```
          ID: org.gnome.Evolution
         Ref: app/org.gnome.Evolution/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.38.2  (3.38.2-1.module_f33+10736+4f8d5006)
     License: GPL-2.0+ and GFDL-1.3
      Origin: fedora
  Collection: 
Installation: system
   Installed: 130.9 MB
     Runtime: org.fedoraproject.Platform/x86_64/f33
         Sdk: org.fedoraproject.Sdk/x86_64/f33

      Commit: 79547960e8f04fa0e0c2caf8ddb34855cc5db22405ab9db454843c76b6cef306
     Subject: Export org.gnome.Evolution
        Date: 2020-11-24 09:11:12 +0000
      Alt-id: cbfbb0847e96fb9050d4325fcd0758fdb09ae87354fa4937f36a72fa2422a30c
```

OS: Fedora Silverblue 33
